### ISSUE TITLE
Kleuren pallet

### ISSUE THREAD

**Issue by WesleySchorel** [kosterm14/connect-your-tribe-squad-page#1]
Je hebt nu een witte achtergrond. Je zou een kleuren pallet kunnen opstellen om je website levendiger te maken.

**Comment by kosterm14** [comment]
Dank je wel ik heb een kleuren palette toegevoegd nu

![image](https://user-images.githubusercontent.com/61830362/230496176-af47c97d-bd15-418f-87b8-c0a0476938c5.png)
