### ISSUE TITLE
Balken

### ISSUE THREAD

**Issue by moonlightlizaa** [kosterm14/connect-your-tribe-squad-page#3]
De gekleurde balken zijn niet gelijk. Dit maakt het een beetje vervelend om naar te kijken.

**Comment by moonlightlizaa** [comment]
<img width="832" alt="Screenshot 2023-02-20 at 11 15 31 AM" src="https://user-images.githubusercontent.com/106411511/220077187-65b30b06-a90c-43e7-80c6-be54f6469d14.png">

**Comment by kosterm14** [comment]
Ik heb ervoor gekozen de balken weg te laten
