### ISSUE TITLE
Hiërarchie 

### ISSUE THREAD

**Issue by moonlightlizaa** [kosterm14/connect-your-tribe-squad-page#4]
Je kan een beetje meer variatie in de grootte of gewicht van de tekst toevoegen. 

<img width="668" alt="Screenshot 2023-02-20 at 11 17 27 AM" src="https://user-images.githubusercontent.com/106411511/220077648-16f3f297-be32-480a-91dc-55ad46a27695.png">

**Comment by kosterm14** [comment]
Ik heb hierover nagedacht en heb nu een duidelijke visuele hiërarchie in de tekst groottes

![image](https://user-images.githubusercontent.com/61830362/230496400-c7229f7a-0e9c-42ad-b371-d84d975a9ccb.png)
